version: 2
jobs:
  build:
    docker:   
      - image: ubuntu # debian:stretch
        environment:
          COLOR: red
          PORT: 8083

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # https://circleci.com/docs/2.0/configuration-reference/#add_ssh_keys
      - add_ssh_keys:
          fingerprints:
            - "36:2d:7e:36:8d:f5:e0:fd:d3:3c:b0:31:ad:ee:26:e6"
            #- "gq9ZdwfeODAMwg42mRBXRDSw6PJ0URxuhPydKtFSyoI"

      - run:
          name: Info
          command: echo "Build:: $CIRCLE_BUILD_NUM (${CIRCLE_BUILD_NUM})"

      - run:
          name: Test SSH
          command: | 
            echo SSH $USER@$SERVER_ADDRESS 
            apt-get update -y
            apt-get install openssh-client -y
            ls -l /usr/bin/ssh

      - run:
          name: Pull Nginx image
          command: | 
            mkdir -p ~/.ssh
            echo "4096 SHA256:gq9ZdwfeODAMwg42mRBXRDSw6PJ0URxuhPydKtFSyoI alex@Alex-PC (RSA)" > ~/.ssh/known_hosts
            #echo $K > ~/.ssh/k
            #ls -l ~/.ssh
            #chmod 600 ~/.ssh/k
            #echo 
            #ssh $USER@$SERVER_ADDRESS -o StrictHostKeyChecking=no -i ~/.ssh/k bash -c '
            ssh $USER@$SERVER_ADDRESS -o StrictHostKeyChecking=no bash -c '
              mkdir -p ~/temp
              touch ~/temp/build_$CIRCLE_BUILD_NUM.txt
            '