version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
        environment:
          COLOR: red
          PORT: 8083

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello

      - run:
          name: Test SSH
          command: echo SSH $USER@$SERVER_ADDRESS

      #- run:
      #  name: Pull Nginx image
      #  command: ssh 