version: 2
jobs:
  build:
    docker:   
      - image: ubuntu # debian:stretch
        environment:
          COLOR: red
          PORT: 8083

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Greeting
          command: echo Hello

      - run:
          name: Test SSH
          command: | 
            echo SSH $USER@$SERVER_ADDRESS -o StrictHostKeyChecking=no
            apt-get update -y
            apt-get install openssh-client -y
            ls -l /usr/bin/ssh

      - run:
          name: Pull Nginx image
          command: | 
            mkdir -p ~/.ssh
            echo $K > ~/.ssh/k
            ssh $USER@$SERVER_ADDRESS -i ~/.ssh/k bash -c '
              mkdir -p ~/temp
              touch ~/temp/${CIRCLE_BUILD_NUM}.txt
            '